name: CI/CD React App

on:
  push:
    branches:
      - main

env:
  NODE_VERSION: 20

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Deploy via SSH (build + sync)
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e

            APP_DIR="/home/sdembele/cicd"
            REPO="https://github.com/Severin-Dembele/ci_cd.git"

            echo " Checking project directory..."

            if [ ! -d "$APP_DIR/.git" ]; then
              rm -rf $APP_DIR
              git clone $REPO $APP_DIR
            fi

            cd $APP_DIR

            echo " Updating code..."
            git reset --hard
            git pull origin main

            echo "Installing dependencies..."
            npm ci

            echo "Building project..."
            npm run build

            echo " Deploying build to Nginx folder..."
            sudo rm -rf /var/www/utm/*
            sudo cp -r dist/* /var/www/utm/

            echo " Fixing permissions..."
            sudo chown -R www-data:www-data /var/www/utm
            sudo chmod -R 755 /var/www/utm

            echo " Reloading Nginx..."
            sudo systemctl reload nginx