name: CI/CD React App

on:
  push:
    branches:
      - main

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Deploy and build on server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            APP_DIR="/home/sdembele/cicd"

            # Cloner ou mettre à jour le repo
            if [ ! -d "$APP_DIR/.git" ]; then
              rm -rf $APP_DIR
              git clone https://github.com/Severin-Dembele/ci_cd.git $APP_DIR
            else
              cd $APP_DIR
              git pull origin main
            fi

            cd $APP_DIR

            # Installer les dépendances et builder
            npm install
            npm run build

            # Copier le build vers /var/www/utm
            echo "Copie du build vers /var/www/utm..."
            echo ${{ secrets.SSH_PASSWORD }} | sudo -S rm -rf /var/www/utm/*
            echo ${{ secrets.SSH_PASSWORD }} | sudo -S cp -r dist/* /var/www/utm/

            # Fixer les permissions
            echo ${{ secrets.SSH_PASSWORD }} | sudo -S chown -R www-data:www-data /var/www/utm
            echo ${{ secrets.SSH_PASSWORD }} | sudo -S chmod -R 755 /var/www/utm

            # Redémarrer Nginx
            echo ${{ secrets.SSH_PASSWORD }} | sudo -S systemctl reload nginx
